#!/bin/sh

# installed by CaptainHook 5.10.11

INTERACTIVE="--no-interaction"

vendor/bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:commit-msg "$@" <&0
